version: '3'
services:
  app:
    container_name: app-server
    image: nextcloud:fpm
    restart: always
    expose:
      - '80'
      - '9000'
    volumes:
      - ./app_data:/var/www/html:rw
  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    environment:
      - USE_UNAUTHORIZED_STORAGE=true
    restart: always
    expose:
      - '80'
      - '443'
    volumes:
      - ./document_data:/var/www/onlyoffice/Data
      - ./document_log:/var/log/onlyoffice
  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/wwwcerts:/etc/nginx/certs:ro
      - ./nginx/nginx-ssl.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/common.conf:/etc/nginx/common.conf:ro
      - app_data:/var/www/html
  mysql:
    image: mysql:${MYSQL_VERSION}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    privileged: true
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
      - ${MYSQL_INITDB_FILE}:/docker-entrypoint-initdb.d/init_db.sql
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      ports:
        - "${PHPMYADMIN_HOST_PORT}:80"
      networks:
        - default
      environment:
        - PMA_HOST=mysql
        - PMA_PORT=3306

networks:
  default:

volumes:
  document_data:
  document_log:
  app_data:
  mysql_data:
