version: "3"
services:  
  
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    privileged: true
    volumes:
      - ./conf/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql:/var/lib/mysql/:rw
      - ./conf/mysql/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "P@ss123456789"
  phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      ports:
        - "8080:80"
      networks:
        - default
      environment:
        - PMA_HOST=mysql
        - PMA_PORT=3306

networks:
  default:
